export const PROMPTS: string[] = [
  // Romance & dating
  'been on a blind date',
  'said "I love you" and not meant it',
  'been stood up on a date',
  'kissed someone on a first date',
  'written a love letter by hand',
  'had a long-distance relationship',
  'dated someone my friends didn\'t approve of',
  'had a celebrity crush so intense it was embarrassing',
  'slid into someone\'s DMs',
  'had a secret relationship',
  'used a cheesy pickup line unironically',
  'gone back to an ex',
  'caught feelings for a close friend',
  'fallen for someone at first sight',
  'been in love with two people at the same time',
  'pretended to like the same things as a crush',
  'changed my appearance to impress someone',
  'practiced saying "I love you" in the mirror',
  'written someone\'s name over and over in a notebook',
  'had a crush on a friend\'s sibling',

  // Relationships & partners
  'snooped on my partner\'s phone',
  'forgotten an anniversary or birthday',
  'said the wrong name at the worst possible moment',
  'been jealous of my partner\'s friend',
  'lied to avoid a date night',
  'planned a surprise that went completely wrong',
  'pretended to be asleep to avoid a conversation',
  'faked liking a meal my partner cooked',
  'accidentally liked an ex\'s old photo while stalking',
  'rehearsed an argument in the shower',
  'cried over a breakup in public',
  'kept a gift from an ex',
  'compared my relationship to someone else\'s',
  'sent a risky text and immediately regretted it',
  'made up a fake excuse to leave a bad date',

  // Embarrassing
  'accidentally sent a text to the wrong person',
  'tripped in public and pretended nothing happened',
  'waved back at someone who wasn\'t waving at me',
  'called a teacher "mom" or "dad" by accident',
  'laughed at something serious because I was nervous',
  'been caught talking to myself',
  'walked into a glass door',
  'forgotten someone\'s name right after they told me',
  'cried during a TV commercial',
  'walked around with something stuck in my teeth all day',
  'replied "you too" when a waiter said "enjoy your meal"',
  'accidentally hit "reply all" on an email',
  'sang out loud not realizing someone was listening',
  'tried to push a pull door in front of people',
  'spilled a drink on someone I was trying to impress',

  // Social
  'pretended to be on the phone to avoid someone',
  'ghosted someone',
  'lied about my age',
  'stalked someone on social media for over an hour',
  'pretended to like a gift I absolutely hated',
  'fake laughed at a joke I didn\'t understand',
  'eavesdropped on a juicy conversation',
  'talked behind someone\'s back and gotten caught',
  'pretended not to see someone I know in public',
  'given a fake phone number',
  'left a party without telling anyone',
  'made up an excuse to not hang out',
  'unfollowed someone and hoped they wouldn\'t notice',
  'screenshot a conversation to send to someone else',
  'accidentally called someone the wrong name for weeks',

  // Food & drink
  'eaten food off the floor',
  'eaten an entire pizza by myself in one sitting',
  'tried to cook a fancy meal and completely failed',
  'eaten something expired without checking the date',
  'double-dipped at a party',
  'eaten cereal for dinner more than three days in a row',
  'pretended to like a food just to be polite',
  'burned something so badly the fire alarm went off',
  'eaten someone else\'s clearly labeled food',
  'licked the plate clean when no one was looking',
  'ordered the same thing at a restaurant every single time',
  'eaten cake or ice cream straight from the container',

  // Adventure & risk
  'gone skinny dipping',
  'snuck out of the house',
  'broken a bone',
  'gotten a speeding ticket',
  'traveled to another country completely alone',
  'bungee jumped or skydived',
  'stayed awake for over 24 hours straight',
  'hitchhiked or picked up a hitchhiker',
  'lied on my resume',
  'called in sick when I was perfectly fine',
  'danced on a table',
  'sang karaoke completely sober',
  'gone on a road trip with no destination in mind',
  'done something just because someone dared me to',

  // Everyday life
  'cried in a movie theater',
  'danced alone in my room like nobody was watching',
  'talked to a pet like it was a real person',
  'had a full conversation with myself out loud',
  'pulled an all-nighter for absolutely no reason',
  'regifted a present someone gave me',
  'worn the same outfit two days in a row hoping no one noticed',
  'spent way too long picking a Netflix show and then not watching anything',
  'set more than 10 alarms to wake up',
  'cried over something completely ridiculous',
  'googled symptoms and convinced myself I was dying',
  'binged an entire TV series in one weekend',
  'kept a secret for years that I\'ve never told anyone',
  'talked my way out of a ticket or fine',
  'laughed so hard I snorted',
];
