export interface Word {
  word: string;
  hint: string;
  points: number;
  alts?: string[];
}

export type GameMode = 'regular' | 'french' | 'dev';
export type TimeMode = 60 | 90 | 120;

export const MODE_LABELS: Record<GameMode, string> = {
  regular: 'Regular',
  french: 'Fran\u00e7ais',
  dev: 'Developer',
};

export const TIME_LABELS: Record<TimeMode, string> = {
  60: '1 min',
  90: '1:30',
  120: '2 min',
};

const regularWords: Word[] = [
  // 4-letter (100 pts)
  { word: 'calm', hint: 'Peaceful and still', points: 100, alts: ['clam'] },
  { word: 'leaf', hint: 'Grows on a tree', points: 100, alts: ['flea'] },
  { word: 'rain', hint: 'Falls from the sky', points: 100 },
  { word: 'pond', hint: 'Small body of water', points: 100 },
  { word: 'bird', hint: 'Creature with wings', points: 100 },
  { word: 'seed', hint: 'Start of a plant', points: 100 },
  { word: 'moon', hint: 'Lights up the night', points: 100, alts: ['mono'] },
  { word: 'wind', hint: 'Moving air', points: 100 },
  { word: 'frog', hint: 'Hops on lily pads', points: 100 },
  { word: 'nest', hint: "A bird's home", points: 100, alts: ['nets', 'tens', 'sent'] },
  { word: 'dawn', hint: 'Start of the day', points: 100, alts: ['wand'] },
  { word: 'dusk', hint: 'End of the day', points: 100 },
  { word: 'mist', hint: 'Thin fog', points: 100, alts: ['smit'] },
  { word: 'pine', hint: 'Evergreen tree', points: 100 },
  { word: 'vine', hint: 'Climbing plant', points: 100, alts: ['vein'] },
  { word: 'root', hint: 'Underground part of a plant', points: 100 },
  { word: 'fern', hint: 'Leafy forest plant', points: 100 },
  { word: 'hike', hint: 'Walk in nature', points: 100 },
  { word: 'moss', hint: 'Soft green ground cover', points: 100 },
  { word: 'haze', hint: 'Slight fog in the air', points: 100 },
  { word: 'glow', hint: 'Soft light', points: 100 },
  { word: 'wave', hint: 'Ocean movement', points: 100 },
  { word: 'path', hint: 'Trail through the woods', points: 100 },
  { word: 'tide', hint: 'Ocean rise and fall', points: 100, alts: ['tied', 'diet', 'edit'] },
  { word: 'bark', hint: 'Tree covering', points: 100 },
  { word: 'cave', hint: 'Hollow in a rock', points: 100 },
  { word: 'dome', hint: 'Rounded roof shape', points: 100, alts: ['mode', 'demo'] },
  { word: 'echo', hint: 'Repeated sound', points: 100 },
  { word: 'folk', hint: 'People in general', points: 100 },
  { word: 'gust', hint: 'Sudden burst of wind', points: 100, alts: ['guts', 'tugs'] },
  { word: 'knot', hint: 'Tied rope', points: 100, alts: ['tonk'] },
  { word: 'loom', hint: 'Weaving device', points: 100 },
  { word: 'myth', hint: 'Ancient story', points: 100 },
  { word: 'opal', hint: 'Iridescent gemstone', points: 100 },
  { word: 'plum', hint: 'Purple fruit', points: 100, alts: ['lump'] },
  { word: 'sage', hint: 'Wise herb', points: 100, alts: ['ages'] },
  { word: 'turf', hint: 'Grass-covered earth', points: 100 },
  { word: 'veil', hint: 'Thin covering', points: 100, alts: ['evil', 'vile', 'live'] },
  { word: 'wren', hint: 'Tiny songbird', points: 100 },
  { word: 'yarn', hint: 'Thread for knitting', points: 100, alts: ['nary'] },
  // 5-letter (150 pts)
  { word: 'bloom', hint: 'Flower opening', points: 150 },
  { word: 'stone', hint: 'Small rock', points: 150, alts: ['notes', 'onset', 'tones'] },
  { word: 'creek', hint: 'Small stream', points: 150 },
  { word: 'shade', hint: 'Cool area under a tree', points: 150, alts: ['heads', 'ashed'] },
  { word: 'petal', hint: 'Part of a flower', points: 150, alts: ['leapt', 'pleat'] },
  { word: 'drift', hint: 'Float gently', points: 150 },
  { word: 'cloud', hint: 'White and fluffy in the sky', points: 150, alts: ['could'] },
  { word: 'trail', hint: 'Forest walkway', points: 150, alts: ['trial'] },
  { word: 'grove', hint: 'Small group of trees', points: 150 },
  { word: 'shore', hint: 'Edge of the water', points: 150, alts: ['horse'] },
  { word: 'light', hint: 'Opposite of dark', points: 150 },
  { word: 'earth', hint: 'Soil beneath your feet', points: 150, alts: ['heart', 'rathe'] },
  { word: 'ocean', hint: 'Vast body of water', points: 150, alts: ['canoe'] },
  { word: 'daisy', hint: 'Simple white flower', points: 150 },
  { word: 'brook', hint: 'Babbling water', points: 150 },
  { word: 'amber', hint: 'Warm golden color', points: 150, alts: ['bream'] },
  { word: 'bliss', hint: 'Perfect happiness', points: 150 },
  { word: 'charm', hint: 'Attractive quality', points: 150, alts: ['march'] },
  { word: 'delta', hint: 'River mouth formation', points: 150, alts: ['dealt'] },
  { word: 'ember', hint: 'Glowing coal', points: 150 },
  { word: 'flora', hint: 'Plant life', points: 150 },
  { word: 'grain', hint: 'Cereal seed', points: 150 },
  { word: 'haven', hint: 'Safe place', points: 150 },
  { word: 'ivory', hint: 'Creamy white', points: 150 },
  { word: 'jewel', hint: 'Precious stone', points: 150 },
  { word: 'knoll', hint: 'Small rounded hill', points: 150 },
  { word: 'lilac', hint: 'Purple flowering shrub', points: 150 },
  { word: 'manor', hint: 'Large country house', points: 150 },
  { word: 'oasis', hint: 'Desert water spot', points: 150 },
  { word: 'quill', hint: 'Feather pen', points: 150 },
  { word: 'reign', hint: 'Rule as monarch', points: 150 },
  { word: 'swift', hint: 'Moving very fast', points: 150 },
  { word: 'thorn', hint: 'Sharp plant spine', points: 150, alts: ['north'] },
  { word: 'unity', hint: 'Being one', points: 150 },
  { word: 'vigor', hint: 'Physical strength', points: 150 },
  { word: 'wheat', hint: 'Golden grain crop', points: 150 },
  // 6-letter (200 pts)
  { word: 'garden', hint: 'Where flowers grow', points: 200, alts: ['danger', 'gander'] },
  { word: 'breeze', hint: 'Gentle wind', points: 200 },
  { word: 'forest', hint: 'Dense collection of trees', points: 200, alts: ['foster', 'fortes'] },
  { word: 'meadow', hint: 'Open grassy field', points: 200 },
  { word: 'canopy', hint: 'Treetop cover', points: 200 },
  { word: 'pebble', hint: 'Smooth small stone', points: 200 },
  { word: 'stream', hint: 'Flowing water', points: 200, alts: ['master'] },
  { word: 'sunset', hint: 'Evening sky colors', points: 200, alts: ['unsets'] },
  { word: 'bamboo', hint: 'Tall fast-growing grass', points: 200 },
  { word: 'bonsai', hint: 'Miniature tree art', points: 200 },
  { word: 'cherry', hint: 'Blossom tree fruit', points: 200 },
  { word: 'clover', hint: 'Lucky if it has four leaves', points: 200 },
  { word: 'gentle', hint: 'Soft and kind', points: 200 },
  { word: 'harbor', hint: 'Sheltered port', points: 200 },
  { word: 'island', hint: 'Land surrounded by water', points: 200 },
  { word: 'nectar', hint: 'Sweet flower liquid', points: 200, alts: ['trance'] },
  { word: 'orchid', hint: 'Elegant exotic flower', points: 200 },
  { word: 'quartz', hint: 'Common crystal', points: 200 },
  { word: 'ripple', hint: 'Small wave on water', points: 200, alts: ['lipper'] },
  { word: 'serene', hint: 'Calm and peaceful', points: 200 },
  { word: 'thrive', hint: 'Grow vigorously', points: 200 },
  { word: 'valley', hint: 'Low area between hills', points: 200 },
  { word: 'zenith', hint: 'Highest point', points: 200 },
  { word: 'aurora', hint: 'Northern lights', points: 200 },
  { word: 'branch', hint: 'Arm of a tree', points: 200 },
  { word: 'canyon', hint: 'Deep narrow valley', points: 200 },
  { word: 'fossil', hint: 'Ancient remains in stone', points: 200 },
  { word: 'turtle', hint: 'Slow shelled creature', points: 200 },
  { word: 'rabbit', hint: 'Hops through meadows', points: 200 },
  { word: 'summer', hint: 'Warmest season', points: 200 },
  { word: 'autumn', hint: 'Leaves change color', points: 200 },
  { word: 'spring', hint: 'Season of new growth', points: 200 },
  { word: 'temple', hint: 'Place of meditation', points: 200, alts: ['pelmet'] },
  { word: 'bridge', hint: 'Crosses over water', points: 200 },
  { word: 'candle', hint: 'Wax light source', points: 200, alts: ['lanced'] },
  { word: 'hollow', hint: 'Empty inside', points: 200 },
  { word: 'voyage', hint: 'Long journey', points: 200 },
  { word: 'wreath', hint: 'Circular decoration', points: 200 },
  { word: 'zephyr', hint: 'Soft gentle breeze', points: 200 },
  // 7-letter (300 pts)
  { word: 'jasmine', hint: 'Fragrant white flower', points: 300 },
  { word: 'lantern', hint: 'Portable light', points: 300 },
  { word: 'glacier', hint: 'Slow-moving ice mass', points: 300, alts: ['gracile'] },
  { word: 'feather', hint: 'Light as a...', points: 300 },
  { word: 'blossom', hint: 'Flower in full bloom', points: 300 },
  { word: 'whisper', hint: 'Speak very softly', points: 300 },
  { word: 'crystal', hint: 'Clear mineral formation', points: 300 },
  { word: 'harmony', hint: 'Perfect balance', points: 300 },
  { word: 'horizon', hint: 'Where earth meets sky', points: 300 },
  { word: 'morning', hint: 'Early part of the day', points: 300 },
  { word: 'thunder', hint: 'Sound after lightning', points: 300 },
  { word: 'shimmer', hint: 'Soft sparkling light', points: 300 },
  { word: 'flutter', hint: 'Light rapid movement', points: 300 },
  { word: 'firefly', hint: 'Glowing night insect', points: 300 },
  { word: 'cascade', hint: 'Small waterfall', points: 300 },
  { word: 'drought', hint: 'Long period without rain', points: 300 },
  { word: 'essence', hint: 'Core nature of something', points: 300 },
  { word: 'verdant', hint: 'Lush and green', points: 300 },
  { word: 'tranquil', hint: 'Extremely peaceful', points: 300 },
  { word: 'solstice', hint: 'Longest or shortest day', points: 300 },
  { word: 'alchemy', hint: 'Medieval chemistry', points: 300 },
  { word: 'balcony', hint: 'Elevated outdoor platform', points: 300 },
  { word: 'chimney', hint: 'Smoke exit on a roof', points: 300 },
  { word: 'daffodil', hint: 'Yellow spring flower', points: 300 },
  { word: 'freckle', hint: 'Small skin spot', points: 300 },
  { word: 'hammock', hint: 'Hanging rest net', points: 300 },
  { word: 'juniper', hint: 'Berry-bearing shrub', points: 300 },
  { word: 'kestrel', hint: 'Small hovering falcon', points: 300, alts: ['skelter'] },
  { word: 'nucleus', hint: 'Center of a cell', points: 300 },
  { word: 'pilgrim', hint: 'Religious traveler', points: 300 },
  // 8+ letter (400 pts)
  { word: 'fragrant', hint: 'Having a pleasant smell', points: 400 },
  { word: 'lavender', hint: 'Purple calming herb', points: 400 },
  { word: 'majestic', hint: 'Grand and impressive', points: 400 },
  { word: 'paradise', hint: 'Perfect peaceful place', points: 400 },
  { word: 'radiance', hint: 'Bright glowing light', points: 400 },
  { word: 'sapphire', hint: 'Blue precious stone', points: 400 },
  { word: 'twilight', hint: 'Light between day and night', points: 400 },
  { word: 'umbrella', hint: 'Rain protection', points: 400 },
  { word: 'wildfire', hint: 'Uncontrolled forest blaze', points: 400 },
  { word: 'solitude', hint: 'Being peacefully alone', points: 400 },
  { word: 'rainfall', hint: 'Water from clouds', points: 400 },
  { word: 'mountain', hint: 'Tall earth formation', points: 400 },
  { word: 'serenity', hint: 'State of calm', points: 400 },
  { word: 'starlight', hint: 'Glow from the night sky', points: 400 },
  { word: 'botanical', hint: 'Related to plants', points: 400 },
  { word: 'evergreen', hint: 'Always has leaves', points: 400 },
  { word: 'moonlight', hint: 'Nighttime illumination', points: 400 },
  { word: 'waterfall', hint: 'Water falling from a cliff', points: 400 },
  { word: 'butterfly', hint: 'Colorful winged insect', points: 400 },
  { word: 'dandelion', hint: 'Fluffy wish flower', points: 400 },
  { word: 'dragonfly', hint: 'Hovering pond insect', points: 400 },
  { word: 'sanctuary', hint: 'Safe peaceful place', points: 400 },
  { word: 'wisteria', hint: 'Cascading purple vine', points: 400 },
  { word: 'enchanted', hint: 'Under a magical spell', points: 400 },
  { word: 'labyrinth', hint: 'Complex maze', points: 400 },
  { word: 'nostalgic', hint: 'Longing for the past', points: 400 },
  { word: 'obsidian', hint: 'Volcanic black glass', points: 400 },
  { word: 'porcelain', hint: 'Fine ceramic material', points: 400 },
  { word: 'quicksand', hint: 'Sinking wet sand', points: 400 },
  { word: 'reservoir', hint: 'Water storage lake', points: 400 },
];

const frenchWords: Word[] = [
  // 4-letter (100 pts)
  { word: 'lune', hint: 'Astre de la nuit', points: 100 },
  { word: 'chat', hint: 'Animal domestique qui ronronne', points: 100 },
  { word: 'vent', hint: 'Mouvement de l\'air', points: 100 },
  { word: 'fleur', hint: 'Pousse dans un jardin', points: 100 },
  { word: 'jour', hint: 'Oppos\u00e9 de la nuit', points: 100 },
  { word: 'pain', hint: 'Aliment de boulangerie', points: 100 },
  { word: 'pont', hint: 'Traverse une rivi\u00e8re', points: 100 },
  { word: 'rose', hint: 'Fleur \u00e9pineuse', points: 100 },
  { word: 'rire', hint: 'Expression de joie', points: 100 },
  { word: 'ciel', hint: 'Au-dessus de nos t\u00eates', points: 100 },
  { word: 'arbre', hint: 'Grand v\u00e9g\u00e9tal en for\u00eat', points: 100 },
  { word: 'nuit', hint: 'Quand le soleil se couche', points: 100 },
  { word: 'pluie', hint: 'Eau qui tombe du ciel', points: 100 },
  { word: 'reve', hint: 'Pendant le sommeil', points: 100 },
  { word: 'lait', hint: 'Boisson blanche', points: 100 },
  { word: 'neige', hint: 'Tombe en hiver, blanche', points: 100 },
  { word: 'fete', hint: 'Occasion de c\u00e9l\u00e9brer', points: 100 },
  { word: 'voix', hint: 'Ce qu\'on entend quand on parle', points: 100 },
  { word: 'paix', hint: 'Oppos\u00e9 de la guerre', points: 100 },
  { word: 'joie', hint: 'Sentiment de bonheur', points: 100 },
  // 5-letter (150 pts)
  { word: 'soleil', hint: '\u00c9toile qui nous r\u00e9chauffe', points: 150 },
  { word: 'maison', hint: 'O\u00f9 on habite', points: 150 },
  { word: 'nuage', hint: 'Flotte dans le ciel', points: 150 },
  { word: 'ocean', hint: 'Grande \u00e9tendue d\'eau sal\u00e9e', points: 150 },
  { word: 'coeur', hint: 'Organe qui bat', points: 150 },
  { word: 'plage', hint: 'Bord de mer avec du sable', points: 150 },
  { word: 'foret', hint: 'Beaucoup d\'arbres ensemble', points: 150 },
  { word: 'terre', hint: 'Notre plan\u00e8te', points: 150 },
  { word: 'herbe', hint: 'Verte sous les pieds', points: 150 },
  { word: 'etoile', hint: 'Brille dans la nuit', points: 150 },
  { word: 'jardin', hint: 'Espace vert pr\u00e8s de la maison', points: 150 },
  { word: 'amour', hint: 'Sentiment profond', points: 150 },
  { word: 'monde', hint: 'L\'ensemble de la Terre', points: 150 },
  { word: 'livre', hint: 'On le lit', points: 150 },
  { word: 'sable', hint: 'Grains fins sur la plage', points: 150 },
  { word: 'perle', hint: 'Bijou de l\'hu\u00eetre', points: 150 },
  { word: 'brise', hint: 'Vent l\u00e9ger', points: 150 },
  { word: 'vague', hint: 'Mouvement de l\'oc\u00e9an', points: 150 },
  { word: 'matin', hint: 'D\u00e9but de la journ\u00e9e', points: 150 },
  { word: 'ligne', hint: 'Trait droit', points: 150 },
  // 6-letter (200 pts)
  { word: 'chateau', hint: 'Grande demeure historique', points: 200 },
  { word: 'lumiere', hint: 'Oppos\u00e9 de l\'obscurit\u00e9', points: 200 },
  { word: 'riviere', hint: 'Cours d\'eau', points: 200 },
  { word: 'papillon', hint: 'Insecte aux ailes color\u00e9es', points: 200 },
  { word: 'montagne', hint: 'Tr\u00e8s haute \u00e9l\u00e9vation de terrain', points: 200 },
  { word: 'automne', hint: 'Saison des feuilles mortes', points: 200 },
  { word: 'chanson', hint: 'Musique avec des paroles', points: 200 },
  { word: 'fromage', hint: 'Aliment fait avec du lait', points: 200 },
  { word: 'village', hint: 'Petite commune rurale', points: 200 },
  { word: 'silence', hint: 'Absence de bruit', points: 200 },
  { word: 'voyage', hint: 'D\u00e9placement lointain', points: 200 },
  { word: 'bonheur', hint: '\u00c9tat de grande joie', points: 200 },
  { word: 'aurore', hint: 'Lumi\u00e8re avant le lever du soleil', points: 200 },
  { word: 'cascade', hint: 'Chute d\'eau naturelle', points: 200 },
  { word: 'douceur', hint: 'Qualit\u00e9 de ce qui est doux', points: 200 },
  { word: 'mystere', hint: 'Ce qui est inexplicable', points: 200 },
  { word: 'horizon', hint: 'Ligne o\u00f9 le ciel touche la terre', points: 200 },
  { word: 'boulange', hint: 'M\u00e9tier du pain', points: 200 },
  { word: 'cerise', hint: 'Petit fruit rouge', points: 200 },
  { word: 'nuance', hint: 'Variation subtile', points: 200 },
  // 7+ letter (300 pts)
  { word: 'merveille', hint: 'Chose extraordinaire', points: 300 },
  { word: 'printemps', hint: 'Saison des fleurs', points: 300 },
  { word: 'chocolat', hint: 'Douceur au cacao', points: 300 },
  { word: 'aventure', hint: 'Exp\u00e9rience palpitante', points: 300 },
  { word: 'harmonie', hint: 'Accord parfait', points: 300 },
  { word: 'liberte', hint: 'Droit fondamental', points: 300 },
  { word: 'croissant', hint: 'Viennoiserie en forme de lune', points: 300 },
  { word: 'fontaine', hint: 'Jet d\'eau d\u00e9coratif', points: 300 },
  { word: 'crepuscule', hint: 'Lumi\u00e8re entre jour et nuit', points: 300 },
  { word: 'lendemain', hint: 'Le jour suivant', points: 300 },
  { word: 'tournesol', hint: 'Fleur qui suit le soleil', points: 300 },
  { word: 'promenade', hint: 'Marche tranquille', points: 300 },
  { word: 'souvenirs', hint: 'Ce qu\'on garde en m\u00e9moire', points: 300 },
  { word: 'esperance', hint: 'Sentiment d\'espoir', points: 300 },
  { word: 'hirondelle', hint: 'Oiseau migrateur', points: 300 },
  // 8+ letter (400 pts)
  { word: 'magnifique', hint: 'Extr\u00eamement beau', points: 400 },
  { word: 'boulangerie', hint: 'Boutique qui vend du pain', points: 400 },
  { word: 'extraordinaire', hint: 'Hors du commun', points: 400 },
  { word: 'bibliotheque', hint: 'Lieu rempli de livres', points: 400 },
  { word: 'constellation', hint: 'Groupe d\'\u00e9toiles', points: 400 },
];

const devWords: Word[] = [
  // 4-letter (100 pts)
  { word: 'bash', hint: 'Unix shell', points: 100 },
  { word: 'node', hint: 'JavaScript runtime', points: 100 },
  { word: 'rust', hint: 'Memory-safe language by Mozilla', points: 100 },
  { word: 'yarn', hint: 'Package manager for JS', points: 100 },
  { word: 'enum', hint: 'Named set of constants', points: 100 },
  { word: 'heap', hint: 'Dynamic memory area', points: 100 },
  { word: 'loop', hint: 'Repeated execution', points: 100 },
  { word: 'pipe', hint: 'Passes output between commands', points: 100 },
  { word: 'json', hint: 'Data format with curly braces', points: 100 },
  { word: 'void', hint: 'Returns nothing', points: 100 },
  { word: 'byte', hint: '8 bits', points: 100 },
  { word: 'grep', hint: 'Search text patterns', points: 100 },
  { word: 'diff', hint: 'Shows file changes', points: 100 },
  { word: 'fork', hint: 'Copy a repo or process', points: 100 },
  { word: 'lint', hint: 'Code style checker', points: 100 },
  { word: 'mock', hint: 'Simulated test object', points: 100 },
  { word: 'hash', hint: 'One-way transformation', points: 100 },
  { word: 'slug', hint: 'URL-friendly string', points: 100 },
  { word: 'port', hint: 'Network connection number', points: 100 },
  { word: 'cron', hint: 'Scheduled job runner', points: 100 },
  // 5-letter (150 pts)
  { word: 'react', hint: 'Facebook UI library', points: 150, alts: ['crate', 'trace'] },
  { word: 'redis', hint: 'In-memory data store', points: 150 },
  { word: 'nginx', hint: 'Web server / reverse proxy', points: 150 },
  { word: 'flask', hint: 'Python web microframework', points: 150 },
  { word: 'oauth', hint: 'Authorization protocol', points: 150 },
  { word: 'regex', hint: 'Pattern matching syntax', points: 150 },
  { word: 'stack', hint: 'LIFO data structure', points: 150 },
  { word: 'queue', hint: 'FIFO data structure', points: 150 },
  { word: 'token', hint: 'Auth credential string', points: 150 },
  { word: 'merge', hint: 'Combine git branches', points: 150 },
  { word: 'fetch', hint: 'HTTP request API', points: 150 },
  { word: 'async', hint: 'Non-blocking execution', points: 150 },
  { word: 'proxy', hint: 'Intermediary server', points: 150 },
  { word: 'tuple', hint: 'Immutable sequence', points: 150 },
  { word: 'cache', hint: 'Stored for fast access', points: 150 },
  { word: 'patch', hint: 'Partial update', points: 150 },
  { word: 'stdin', hint: 'Standard input stream', points: 150 },
  { word: 'debug', hint: 'Find and fix bugs', points: 150 },
  { word: 'query', hint: 'Database question', points: 150 },
  { word: 'epoch', hint: 'Unix timestamp origin', points: 150 },
  // 6-letter (200 pts)
  { word: 'docker', hint: 'Container platform', points: 200 },
  { word: 'lambda', hint: 'AWS serverless functions', points: 200 },
  { word: 'python', hint: 'Language named after a snake', points: 200 },
  { word: 'github', hint: 'Code hosting platform', points: 200 },
  { word: 'cursor', hint: 'Database result pointer', points: 200 },
  { word: 'heroku', hint: 'Cloud PaaS platform', points: 200 },
  { word: 'subnet', hint: 'Network subdivision', points: 200 },
  { word: 'sprint', hint: 'Agile work period', points: 200 },
  { word: 'deploy', hint: 'Ship code to production', points: 200 },
  { word: 'bucket', hint: 'S3 storage container', points: 200 },
  { word: 'socket', hint: 'Network communication endpoint', points: 200 },
  { word: 'schema', hint: 'Database structure definition', points: 200 },
  { word: 'kernel', hint: 'OS core', points: 200 },
  { word: 'binary', hint: 'Base-2 number system', points: 200 },
  { word: 'thread', hint: 'Unit of execution', points: 200 },
  { word: 'module', hint: 'Code unit with exports', points: 200 },
  { word: 'render', hint: 'Display output / cloud host', points: 200 },
  { word: 'cursor', hint: 'Blinking text position', points: 200 },
  { word: 'commit', hint: 'Git snapshot', points: 200 },
  { word: 'branch', hint: 'Git parallel line of work', points: 200 },
  // 7-letter (300 pts)
  { word: 'terraform', hint: 'Infrastructure as code tool', points: 300 },
  { word: 'webpack', hint: 'JavaScript module bundler', points: 300 },
  { word: 'graphql', hint: 'Query language for APIs', points: 300 },
  { word: 'ansible', hint: 'Config management tool', points: 300 },
  { word: 'jenkins', hint: 'CI/CD automation server', points: 300 },
  { word: 'mongodb', hint: 'NoSQL document database', points: 300 },
  { word: 'fargate', hint: 'AWS serverless containers', points: 300 },
  { word: 'dynamo', hint: 'AWS NoSQL database', points: 300 },
  { word: 'kinesis', hint: 'AWS real-time streaming', points: 300 },
  { word: 'boolean', hint: 'True or false type', points: 300 },
  { word: 'runtime', hint: 'Execution environment', points: 300 },
  { word: 'swagger', hint: 'API documentation tool', points: 300 },
  { word: 'webhook', hint: 'HTTP callback', points: 300 },
  { word: 'payload', hint: 'Request body data', points: 300 },
  { word: 'gateway', hint: 'API entry point', points: 300 },
  // 8+ letter (400 pts)
  { word: 'kubernetes', hint: 'Container orchestration K8s', points: 400 },
  { word: 'typescript', hint: 'Typed JavaScript superset', points: 400 },
  { word: 'cloudfront', hint: 'AWS CDN service', points: 400 },
  { word: 'cloudwatch', hint: 'AWS monitoring service', points: 400 },
  { word: 'elasticache', hint: 'AWS managed Redis/Memcached', points: 400 },
  { word: 'sagemaker', hint: 'AWS machine learning platform', points: 400 },
  { word: 'codepipeline', hint: 'AWS CI/CD service', points: 400 },
  { word: 'cloudformation', hint: 'AWS infra as JSON/YAML', points: 400 },
  { word: 'middleware', hint: 'Request processing layer', points: 400 },
  { word: 'repository', hint: 'Code storage location', points: 400 },
  { word: 'serializer', hint: 'Object to format converter', points: 400 },
  { word: 'encryption', hint: 'Data scrambling for security', points: 400 },
  { word: 'microservice', hint: 'Small independent service', points: 400 },
  { word: 'pagination', hint: 'Splitting results into pages', points: 400 },
  { word: 'idempotent', hint: 'Same result on repeated calls', points: 400 },
];

export const wordsByMode: Record<GameMode, Word[]> = {
  regular: regularWords,
  french: frenchWords,
  dev: devWords,
};

export const allWords = regularWords;
