import { Scenario } from './types';

export const SCENARIOS: Scenario[] = [
  { situation: "You find a locked pharmacy.", optionA: "Break in and search for supplies", optionB: "Keep moving — too risky" },
  { situation: "You discover an abandoned school.", optionA: "Set up base camp inside", optionB: "Sleep on the roof where zombies can't reach" },
  { situation: "A bridge ahead is partially collapsed.", optionA: "Cross carefully on foot", optionB: "Find another route even if it takes hours" },
  { situation: "You spot a military checkpoint — it looks deserted.", optionA: "Investigate for weapons", optionB: "Avoid it — could be a trap" },
  { situation: "There's a working elevator in an office building.", optionA: "Take the elevator to the top floor", optionB: "Use the stairs — elevators are death traps" },
  { situation: "You find an underground bunker with a sealed door.", optionA: "Try to break in", optionB: "It's sealed for a reason — leave it" },
  { situation: "A luxury car with keys in the ignition.", optionA: "Take the car and drive", optionB: "Cars attract too much attention — walk" },
  { situation: "An island is visible across a river.", optionA: "Swim across to safety", optionB: "Stay on land where you can run" },
  { situation: "You find a shopping mall with intact shutters.", optionA: "Hole up inside the mall", optionB: "Malls are death traps — keep moving" },
  { situation: "A church with a bell tower.", optionA: "Climb the tower for a vantage point", optionB: "Bells attract zombies — avoid" },
  { situation: "You find a vending machine full of food.", optionA: "Smash it open loudly", optionB: "Leave it — the noise will draw them" },
  { situation: "Your water supply is running low. You see a creek.", optionA: "Drink it — risk getting sick", optionB: "Keep rationing what you have" },
  { situation: "Abandoned gas station with a generator.", optionA: "Fire it up for power", optionB: "Generators are loud — pass" },
  { situation: "A dead survivor has a fully loaded weapon.", optionA: "Take it", optionB: "Could be bait from raiders — leave it" },
  { situation: "You find canned food, but the cans are swollen.", optionA: "Eat it — food is food", optionB: "Toss it — botulism kills faster than zombies" },
  { situation: "A working radio picks up a distress signal.", optionA: "Follow the signal", optionB: "It could be a trap to lure survivors" },
  { situation: "You find antibiotics, but they expired months ago.", optionA: "Take them anyway", optionB: "Expired meds could make things worse" },
  { situation: "A bag of seeds and some soil.", optionA: "Plant a garden and stay put", optionB: "Seeds won't help you survive the week" },
  { situation: "Solar panels on a rooftop.", optionA: "Set up a charging station", optionB: "Waste of time — keep moving" },
  { situation: "You find fireworks.", optionA: "Save them as a distraction tool", optionB: "Too dangerous to carry around" },
  { situation: "A stranger is banging on your door at night.", optionA: "Let them in", optionB: "Too risky — ignore them" },
  { situation: "One of your group is sick and slowing you down.", optionA: "Stay together no matter what", optionB: "Leave them behind — survival of the fittest" },
  { situation: "A child is alone and crying in the street.", optionA: "Help the child", optionB: "It could be a trap — keep going" },
  { situation: "Two groups want to merge with yours.", optionA: "Accept both groups", optionB: "Stay small — big groups attract attention" },
  { situation: "Someone in your group stole rations.", optionA: "Confront them publicly", optionB: "Let it go to keep the peace" },
  { situation: "An injured stranger offers to trade intel for shelter.", optionA: "Take the deal", optionB: "Trust no one — refuse" },
  { situation: "Your group disagrees on which direction to travel.", optionA: "Go north toward the mountains", optionB: "Go south toward the coast" },
  { situation: "A former doctor wants to join but demands leadership.", optionA: "Accept their terms", optionB: "No one gets special treatment" },
  { situation: "You find a lone wolf survivor who is clearly dangerous.", optionA: "Recruit them — you need fighters", optionB: "Dangerous people are liabilities" },
  { situation: "You discover another group has been following you.", optionA: "Confront them", optionB: "Lose them by changing course" },
  { situation: "A horde is approaching. You have one Molotov cocktail.", optionA: "Throw it at the horde", optionB: "Save it for a more desperate moment" },
  { situation: "You hear gunfire in the distance.", optionA: "Investigate — other survivors", optionB: "Avoid — gunfire attracts zombies" },
  { situation: "You're cornered in an alley with two exits.", optionA: "Take the narrow path through buildings", optionB: "Make a run for the open street" },
  { situation: "A zombie is trapped behind a door.", optionA: "Kill it now while it's contained", optionB: "Leave it — save your energy" },
  { situation: "You find a chainsaw with half a tank of gas.", optionA: "Take it as a weapon", optionB: "Too loud and heavy — stick with melee" },
  { situation: "A pack of wild dogs is blocking your path.", optionA: "Try to scare them off", optionB: "Find an alternate route" },
  { situation: "You see a sniper on a rooftop.", optionA: "Wave and try to communicate", optionB: "Take cover — they might shoot anything" },
  { situation: "A building is about to collapse with zombies inside.", optionA: "Trigger the collapse to kill them", optionB: "Collapsed buildings block escape routes" },
  { situation: "You can set a car alarm to distract a horde.", optionA: "Set it off and run the other way", optionB: "Car alarms attract MORE zombies" },
  { situation: "Nightfall is coming and you have no shelter.", optionA: "Travel through the night", optionB: "Find the nearest building and barricade" },
  { situation: "You find a survivor who's been bitten but not yet turned.", optionA: "Put them down before they turn", optionB: "Wait — maybe they're immune" },
  { situation: "A friendly group has food but won't share.", optionA: "Steal from them at night", optionB: "Respect their decision and move on" },
  { situation: "You can save two strangers OR keep all your supplies.", optionA: "Share your supplies", optionB: "Your group comes first" },
  { situation: "An old friend appears, but they've been acting strange.", optionA: "Welcome them back", optionB: "Quarantine them first" },
  { situation: "A working phone booth. You could call for help.", optionA: "Make the call", optionB: "Phone lines might be monitored by hostiles" },
  { situation: "A child has a pet dog that barks constantly.", optionA: "The dog has to go", optionB: "The kid needs the dog for morale" },
  { situation: "You find a scientist's journal about the infection.", optionA: "Spend time reading it", optionB: "No time for research — keep surviving" },
  { situation: "Someone wants to go back for a family member.", optionA: "Help them go back", optionB: "It's a suicide mission — refuse" },
  { situation: "You discover a cure might exist across the city.", optionA: "Risk the journey", optionB: "It's probably a rumor — stay safe" },
  { situation: "A dying survivor begs you to find their family.", optionA: "Promise to find them", optionB: "You can't make promises you can't keep" },
  { situation: "You find a boat but it has a hole in it.", optionA: "Patch it and sail", optionB: "A sinking boat is worse than no boat" },
  { situation: "A helicopter sits on a rooftop. You've never flown one.", optionA: "Try to fly it", optionB: "Crashing is worse than walking" },
  { situation: "A tunnel could be a shortcut but it's pitch dark.", optionA: "Go through the tunnel", optionB: "Take the long way above ground" },
  { situation: "You find dynamite at a construction site.", optionA: "Take it — massive firepower", optionB: "One wrong move and you're dead" },
  { situation: "A zoo's fences have broken. Large animals roam free.", optionA: "Cut through the zoo", optionB: "Wild animals are as dangerous as zombies" },
  { situation: "A frozen lake is the fastest route.", optionA: "Cross the ice", optionB: "Go around — falling through means death" },
  { situation: "You can climb a crane for the ultimate vantage point.", optionA: "Climb it", optionB: "One slip and you're gone" },
  { situation: "An underground metro tunnel leads downtown.", optionA: "Enter the metro", optionB: "Underground means no escape routes" },
  { situation: "A hot air balloon is partially inflated.", optionA: "Try to get it airborne", optionB: "One bullet from the sky and you're done" },
  { situation: "You find a working motorcycle but the roads are jammed.", optionA: "Weave through traffic on the bike", optionB: "Motorcycles are loud and exposed" },
];
