export const PROMPTS: string[] = [
  // Social norms
  'How acceptable is it to ghost someone after one date?',
  'How weird is it to eat lunch alone at a restaurant?',
  'How acceptable is it to cancel plans last minute?',
  'How normal is it to talk to yourself out loud?',
  'How weird is it to go to a movie theater alone?',
  'How acceptable is it to read someone\'s texts over their shoulder?',
  'How normal is it to have zero social media accounts?',
  'How weird is it to befriend your ex\'s new partner?',
  'How acceptable is it to not tip at a sit-down restaurant?',
  'How normal is it to cry in public?',
  'How acceptable is it to recline your seat on an airplane?',
  'How weird is it to wave back at someone who wasn\'t waving at you?',
  'How acceptable is it to take a phone call on speaker in public?',
  'How normal is it to eavesdrop on strangers\' conversations?',
  'How weird is it to clap when the plane lands?',
  'How acceptable is it to cut in line if you\'re in a rush?',
  'How normal is it to sing along to music in public?',
  'How weird is it to make eye contact with strangers on the subway?',
  'How acceptable is it to bring outside food into a movie theater?',
  'How normal is it to have an imaginary argument in the shower?',

  // Food opinions
  'How acceptable is it to eat cereal for dinner?',
  'How weird is it to put ketchup on scrambled eggs?',
  'How acceptable is it to eat pizza with a fork and knife?',
  'How normal is it to dip french fries in a milkshake?',
  'How weird is it to eat dessert before the main course?',
  'How acceptable is it to ask for a doggy bag on a first date?',
  'How normal is it to put pineapple on pizza?',
  'How weird is it to eat the same meal every single day?',
  'How acceptable is it to double-dip a chip at a party?',
  'How normal is it to drink coffee after 8pm?',
  'How weird is it to eat a burger with a fork and knife?',
  'How acceptable is it to drink milk with dinner as an adult?',
  'How normal is it to eat cold leftover pizza for breakfast?',
  'How weird is it to put ranch dressing on everything?',
  'How acceptable is it to send back food at a restaurant?',

  // Relationships & dating
  'How acceptable is it to check your partner\'s phone?',
  'How weird is it to keep photos of your ex on social media?',
  'How acceptable is it to date a close friend\'s ex?',
  'How normal is it to have a crush on a coworker?',
  'How acceptable is it to break up over text?',
  'How weird is it to propose after less than six months?',
  'How normal is it to have separate finances in a marriage?',
  'How acceptable is it to say "I love you" on the first date?',
  'How weird is it to follow your crush\'s family on Instagram?',
  'How acceptable is it to keep secrets from your partner?',
  'How normal is it to stay friends with all your exes?',
  'How weird is it to rehearse conversations before having them?',

  // Work & career
  'How acceptable is it to take a sick day when you\'re not sick?',
  'How weird is it to eat someone else\'s labeled food from the office fridge?',
  'How acceptable is it to job hunt while currently employed?',
  'How normal is it to cry at work?',
  'How weird is it to add your boss on social media?',
  'How acceptable is it to take credit for a team effort?',
  'How normal is it to nap during work from home?',
  'How acceptable is it to quiet-quit a job you hate?',
  'How weird is it to turn your camera off during every meeting?',
  'How normal is it to Slack your coworker instead of walking 10 feet?',

  // Daily life
  'How weird is it to shower at night instead of in the morning?',
  'How acceptable is it to wear pajamas to the grocery store?',
  'How normal is it to sleep with socks on?',
  'How acceptable is it to never make your bed?',
  'How normal is it to talk to your pets like they\'re humans?',
  'How weird is it to use your phone while sitting on the toilet?',
  'How acceptable is it to not wash your jeans for a month?',
  'How normal is it to have a strong opinion about how to load a dishwasher?',
  'How weird is it to narrate your own life in your head?',
  'How acceptable is it to use the same towel for a whole week?',
  'How normal is it to set 10+ alarms to wake up?',
  'How weird is it to keep every box from every product you buy?',
  'How acceptable is it to pee in the shower?',

  // Hypotheticals
  'How comfortable would you be living without your phone for a month?',
  'How likely are you to survive a zombie apocalypse?',
  'How willing would you be to eat a bug for $100?',
  'How comfortable are you with public speaking?',
  'How much do you trust strangers?',
  'How likely would you be to pick up a hitchhiker?',
  'How comfortable are you swimming in the ocean at night?',
  'How willing would you be to move to a country where you don\'t speak the language?',
  'How likely are you to run into a burning building to save a stranger?',
  'How comfortable would you be going a full year without the internet?',
  'How willing would you be to shave your head for $500?',
  'How likely are you to confront someone cutting in line?',
  'How comfortable are you sleeping with the door unlocked?',
  'How willing would you be to give up music forever for $1 million?',
  'How likely are you to return a wallet you found with $500 in it?',

  // Spicy takes
  'How overrated is going to the gym?',
  'How important is it to text back within an hour?',
  'How much does astrology actually matter?',
  'How overrated are birthday parties after age 25?',
  'How important is it for couples to have matching energy levels?',
  'How overrated is brunch?',
  'How important is having a five-year plan?',
  'How overrated are weddings?',
  'How important is it to keep a clean car?',
  'How overrated is hustle culture?',
  'How important is having the same music taste as your partner?',
  'How overrated is New Year\'s Eve?',
  'How important is it to be on time?',
  'How overrated are diamonds?',
  'How important is a firm handshake?',
];
