import { Question } from './types';

export const questions: Question[] = [

  // ── PATTERN MATCH ─ Easy ──────────────────────────────────

  {
    type: 'pattern', topic: 'binary-search', difficulty: 'easy',
    prompt: 'You need to find if a target exists in a sorted array of 1 million elements. Which approach is most efficient?',
    options: ['Linear search O(n)', 'Binary search O(log n)', 'Hash set O(1)', 'Sort then search O(n log n)'],
    answer: 1,
    explanation: 'Binary search on a sorted array gives O(log n). Only ~20 comparisons needed for 1 million elements.',
  },
  {
    type: 'pattern', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'Count the frequency of each character in a string. Which data structure is best?',
    options: ['Array of booleans', 'Sorted array', 'Hash map', 'Linked list'],
    answer: 2,
    explanation: 'A hash map stores key-value pairs, perfect for mapping each character to its count in O(n) time.',
  },
  {
    type: 'pattern', topic: 'stacks-queues', difficulty: 'easy',
    prompt: 'Check if a string of parentheses like "({[]})" is balanced. Which data structure helps?',
    options: ['Queue', 'Hash map', 'Stack', 'Array with two pointers'],
    answer: 2,
    explanation: 'A stack lets you push opening brackets and pop when you find the matching closer.',
  },
  {
    type: 'pattern', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'Given an array, find two numbers that add up to a target. What\'s the optimal approach?',
    options: ['Sort + binary search', 'Brute force all pairs', 'Hash map for complements', 'Divide and conquer'],
    answer: 2,
    explanation: 'Store each number in a hash map. For each element, check if (target - element) exists. O(n) time.',
  },
  {
    type: 'pattern', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'Remove all duplicate values from an unsorted array. Most efficient approach?',
    options: ['Nested loops comparing every pair', 'Sort then compare adjacent', 'Hash set to track seen values', 'Binary search for each element'],
    answer: 2,
    explanation: 'A hash set tracks seen values in O(1) per lookup, giving O(n) total time.',
  },
  {
    type: 'pattern', topic: 'two-pointers', difficulty: 'easy',
    prompt: 'Check if a string is a palindrome using O(1) extra space.',
    options: ['Reverse and compare', 'Hash map of character counts', 'Two pointers from both ends', 'Stack-based comparison'],
    answer: 2,
    explanation: 'Two pointers start at the beginning and end, comparing characters inward. O(n) time, O(1) space.',
  },
  {
    type: 'pattern', topic: 'trees-graphs', difficulty: 'easy',
    prompt: 'Traverse a binary tree level by level (left to right). Which approach?',
    options: ['DFS preorder', 'DFS inorder', 'BFS with a queue', 'Stack-based postorder'],
    answer: 2,
    explanation: 'BFS with a queue processes nodes level by level, giving left-to-right level-order traversal.',
  },
  {
    type: 'pattern', topic: 'sliding-window', difficulty: 'easy',
    prompt: 'Find the maximum sum of any k consecutive elements in an array.',
    options: ['Sort the array', 'Sliding window', 'Dynamic programming', 'Binary search'],
    answer: 1,
    explanation: 'A sliding window of size k slides right, adding the new element and removing the leftmost. O(n) time.',
  },

  // ── PATTERN MATCH ─ Medium ────────────────────────────────

  {
    type: 'pattern', topic: 'two-pointers', difficulty: 'medium',
    prompt: 'Given a sorted array, find a pair that sums to a target with O(1) extra space.',
    options: ['Hash map', 'Two pointers from both ends', 'Binary search for each element', 'Sliding window'],
    answer: 1,
    explanation: 'Two pointers start at ends. If sum < target, move left right. If sum > target, move right left. O(n) time, O(1) space.',
  },
  {
    type: 'pattern', topic: 'sliding-window', difficulty: 'medium',
    prompt: 'Find the longest substring without repeating characters.',
    options: ['Dynamic programming', 'Sliding window with hash set', 'Recursion', 'Sort the string first'],
    answer: 1,
    explanation: 'A sliding window expands right and shrinks from left when a duplicate is found. O(n) time.',
  },
  {
    type: 'pattern', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'Find the shortest path between two nodes in an unweighted graph.',
    options: ['Depth-First Search', 'Breadth-First Search', 'Dijkstra\'s algorithm', 'Binary search'],
    answer: 1,
    explanation: 'BFS explores level by level, guaranteeing the shortest path in an unweighted graph.',
  },
  {
    type: 'pattern', topic: 'stacks-queues', difficulty: 'medium',
    prompt: 'Design a data structure with push, pop, and getMin all in O(1).',
    options: ['Single stack with sorting', 'Two stacks (main + min tracker)', 'Priority queue', 'Hash map with min variable'],
    answer: 1,
    explanation: 'A min-stack uses a second stack to track the minimum at each level. All operations are O(1).',
  },
  {
    type: 'pattern', topic: 'binary-search', difficulty: 'medium',
    prompt: 'Find the insertion position for a value in a sorted array to keep it sorted.',
    options: ['Linear scan from start', 'Binary search for lower bound', 'Two pointers', 'Hash map lookup'],
    answer: 1,
    explanation: 'Binary search for the lower bound finds the insertion point in O(log n) time.',
  },
  {
    type: 'pattern', topic: 'stacks-queues', difficulty: 'medium',
    prompt: 'Evaluate a Reverse Polish Notation expression like ["2","1","+","3","*"].',
    options: ['Recursion', 'Stack', 'Queue', 'Two pointers'],
    answer: 1,
    explanation: 'Push numbers onto a stack. On an operator, pop two operands, compute, push the result.',
  },
  {
    type: 'pattern', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'Group strings by their anagrams (e.g., ["eat","tea","tan","ate","nat","bat"]).',
    options: ['Sort all strings globally', 'Hash map with sorted string as key', 'Trie data structure', 'Two pointers on each pair'],
    answer: 1,
    explanation: 'Sort each string to get a canonical form. Use it as a hash map key. Anagrams share the same sorted form.',
  },
  {
    type: 'pattern', topic: 'dynamic-programming', difficulty: 'medium',
    prompt: 'Count unique paths from top-left to bottom-right of an m×n grid (only right or down).',
    options: ['BFS', 'DFS with backtracking', 'Dynamic programming', 'Greedy'],
    answer: 2,
    explanation: 'dp[i][j] = dp[i-1][j] + dp[i][j-1]. Each cell = paths from above + from left.',
  },
  {
    type: 'pattern', topic: 'recursion-backtracking', difficulty: 'medium',
    prompt: 'Find all subsets of a set of distinct integers.',
    options: ['Sliding window', 'BFS level by level', 'Backtracking with include/exclude', 'Two pointers'],
    answer: 2,
    explanation: 'For each element, choose to include or exclude it. This builds 2ⁿ subsets through backtracking.',
  },
  {
    type: 'pattern', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'Determine if a binary tree is a valid Binary Search Tree.',
    options: ['Check each node > left and < right child', 'DFS with min/max range tracking', 'BFS level-order comparison', 'Compare with sorted inorder'],
    answer: 1,
    explanation: 'DFS passing a valid range (min, max) down the tree. Each node must be within its ancestor-derived range.',
  },

  // ── PATTERN MATCH ─ Hard ──────────────────────────────────

  {
    type: 'pattern', topic: 'sliding-window', difficulty: 'hard',
    prompt: 'Find the minimum window in string S containing all characters of string T.',
    options: ['Sort both strings', 'Dynamic programming', 'Sliding window with frequency map', 'Trie-based search'],
    answer: 2,
    explanation: 'Expand window to include all chars of T, then shrink from left to minimize. O(n) with a frequency map.',
  },
  {
    type: 'pattern', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'Given n items with weights and values, maximize total value within a weight limit (0/1 Knapsack).',
    options: ['Greedy by value/weight ratio', 'Dynamic programming', 'Backtracking only', 'Binary search'],
    answer: 1,
    explanation: 'DP builds a table of max values for each capacity. dp[i][w] = max of including or excluding item i.',
  },
  {
    type: 'pattern', topic: 'recursion-backtracking', difficulty: 'hard',
    prompt: 'Generate all valid combinations of n pairs of parentheses.',
    options: ['Dynamic programming', 'BFS level by level', 'Backtracking with open/close counts', 'Stack-based iteration'],
    answer: 2,
    explanation: 'Backtrack by adding "(" when open < n and ")" when close < open. Generates only valid combinations.',
  },
  {
    type: 'pattern', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'Find the length of the longest increasing subsequence in an array.',
    options: ['Sliding window', 'Sort + two pointers', 'DP with binary search (patience sort)', 'Hash map counting'],
    answer: 2,
    explanation: 'DP gives O(n²). Optimized: maintain a tails array and use binary search for O(n log n).',
  },
  {
    type: 'pattern', topic: 'trees-graphs', difficulty: 'hard',
    prompt: 'Detect a cycle in a directed graph.',
    options: ['BFS only', 'DFS with three-color marking', 'Union-Find', 'Two pointers'],
    answer: 1,
    explanation: 'DFS with white/gray/black coloring detects back edges (gray→gray), which indicate cycles.',
  },
  {
    type: 'pattern', topic: 'binary-search', difficulty: 'hard',
    prompt: 'Find the kth smallest element in a matrix where each row and column is sorted.',
    options: ['Flatten and sort', 'Binary search on value range', 'BFS from top-left', 'Sliding window'],
    answer: 1,
    explanation: 'Binary search on [min, max] and count elements ≤ mid. Adjust bounds based on count vs k.',
  },

  // ── BIG O ─ Easy ──────────────────────────────────────────

  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What is the time complexity?',
    code: 'function sum(arr) {\n  let total = 0;\n  for (let i = 0; i < arr.length; i++) {\n    total += arr[i];\n  }\n  return total;\n}',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    answer: 2,
    explanation: 'A single loop through n elements = O(n).',
  },
  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What is the time complexity?',
    code: 'function findPairs(arr) {\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = i + 1; j < arr.length; j++) {\n      console.log(arr[i], arr[j]);\n    }\n  }\n}',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2ⁿ)'],
    answer: 2,
    explanation: 'Nested loops = n*(n-1)/2 iterations = O(n²).',
  },
  {
    type: 'bigO', topic: 'binary-search', difficulty: 'easy',
    prompt: 'What is the time complexity?',
    code: 'function search(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    answer: 1,
    explanation: 'Binary search halves the search space each step = O(log n).',
  },
  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What is the time complexity of accessing arr[5] in an array?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
    answer: 2,
    explanation: 'Array index access is O(1) — direct memory address calculation.',
  },
  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What is the time complexity?',
    code: 'function process(arr) {\n  for (let i = 0; i < arr.length; i++) {\n    arr[i] *= 2;\n  }\n  for (let i = 0; i < arr.length; i++) {\n    console.log(arr[i]);\n  }\n}',
    options: ['O(n²)', 'O(2n) = O(n)', 'O(n log n)', 'O(1)'],
    answer: 1,
    explanation: 'Two sequential O(n) loops = O(n) + O(n) = O(2n) = O(n).',
  },
  {
    type: 'bigO', topic: 'trees-graphs', difficulty: 'easy',
    prompt: 'What is the time complexity of searching in a balanced BST with n nodes?',
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    answer: 1,
    explanation: 'A balanced BST has height log n. Search compares at each level = O(log n).',
  },
  {
    type: 'bigO', topic: 'recursion-backtracking', difficulty: 'easy',
    prompt: 'What is the space complexity of a recursive function with depth n and no extra data?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    answer: 1,
    explanation: 'Each recursive call adds a frame to the call stack. Depth n = O(n) space.',
  },

  // ── BIG O ─ Medium ────────────────────────────────────────

  {
    type: 'bigO', topic: 'recursion-backtracking', difficulty: 'medium',
    prompt: 'What is the time complexity?',
    code: 'function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  return merge(left, right);\n}',
    options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'],
    answer: 1,
    explanation: 'Divides in half (log n levels), merges n elements per level = O(n log n).',
  },
  {
    type: 'bigO', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'What is the time complexity of DFS on a graph with V vertices and E edges?',
    options: ['O(V)', 'O(E)', 'O(V + E)', 'O(V × E)'],
    answer: 2,
    explanation: 'DFS visits each vertex once (V) and traverses each edge once (E) = O(V + E).',
  },
  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'What is the average time complexity of a hash map lookup?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'],
    answer: 2,
    explanation: 'Hash maps provide O(1) average lookup. Worst case is O(n) with collisions.',
  },
  {
    type: 'bigO', topic: 'stacks-queues', difficulty: 'medium',
    prompt: 'What is the time complexity?',
    code: 'function nextGreater(arr) {\n  const result = new Array(arr.length).fill(-1);\n  const stack = [];\n  for (let i = 0; i < arr.length; i++) {\n    while (stack.length && arr[stack[stack.length-1]] < arr[i]) {\n      result[stack.pop()] = arr[i];\n    }\n    stack.push(i);\n  }\n  return result;\n}',
    options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n³)'],
    answer: 2,
    explanation: 'Each element is pushed and popped at most once = O(n) total, despite the nested while loop.',
  },
  {
    type: 'bigO', topic: 'two-pointers', difficulty: 'medium',
    prompt: 'What is the time complexity?',
    code: 'function twoSum(sorted, target) {\n  let l = 0, r = sorted.length - 1;\n  while (l < r) {\n    const sum = sorted[l] + sorted[r];\n    if (sum === target) return [l, r];\n    if (sum < target) l++;\n    else r--;\n  }\n  return [-1, -1];\n}',
    options: ['O(n²)', 'O(n)', 'O(log n)', 'O(n log n)'],
    answer: 1,
    explanation: 'Two pointers move towards each other, covering at most n steps total = O(n).',
  },
  {
    type: 'bigO', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'What is the time complexity?',
    code: 'function hasDuplicate(arr) {\n  const seen = new Set();\n  for (const num of arr) {\n    if (seen.has(num)) return true;\n    seen.add(num);\n  }\n  return false;\n}',
    options: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'],
    answer: 1,
    explanation: 'One pass. Set has/add are O(1) average. Total = O(n).',
  },
  {
    type: 'bigO', topic: 'sliding-window', difficulty: 'medium',
    prompt: 'What is the time complexity of finding the longest substring without repeating characters using a sliding window?',
    options: ['O(n²)', 'O(n)', 'O(n log n)', 'O(26n)'],
    answer: 1,
    explanation: 'Each character is added and removed at most once. Both pointers traverse n total = O(n).',
  },
  {
    type: 'bigO', topic: 'dynamic-programming', difficulty: 'medium',
    prompt: 'What is the time complexity of the 0/1 knapsack with n items and capacity W?',
    options: ['O(n × W)', 'O(2ⁿ)', 'O(n²)', 'O(n log W)'],
    answer: 0,
    explanation: 'The DP table has n rows and W+1 columns. Each cell is O(1) = O(n × W) total.',
  },
  {
    type: 'bigO', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'What is the time complexity of BFS on a graph with an adjacency list?',
    options: ['O(V²)', 'O(V + E)', 'O(V × E)', 'O(E log V)'],
    answer: 1,
    explanation: 'BFS visits each vertex once (V) and examines each edge once (E) = O(V + E).',
  },

  // ── BIG O ─ Hard ──────────────────────────────────────────

  {
    type: 'bigO', topic: 'recursion-backtracking', difficulty: 'hard',
    prompt: 'What is the time complexity of generating all subsets of n elements?',
    options: ['O(n²)', 'O(n!)', 'O(2ⁿ)', 'O(n × 2ⁿ)'],
    answer: 3,
    explanation: 'There are 2ⁿ subsets, and building each takes up to O(n) work = O(n × 2ⁿ).',
  },
  {
    type: 'bigO', topic: 'recursion-backtracking', difficulty: 'hard',
    prompt: 'What is the time complexity of generating all permutations of n elements?',
    options: ['O(2ⁿ)', 'O(n!)', 'O(n × n!)', 'O(nⁿ)'],
    answer: 2,
    explanation: 'There are n! permutations, each requiring O(n) to build = O(n × n!).',
  },
  {
    type: 'bigO', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'What is the time complexity?',
    code: 'function fib(n, memo = {}) {\n  if (n <= 1) return n;\n  if (memo[n]) return memo[n];\n  memo[n] = fib(n-1, memo) + fib(n-2, memo);\n  return memo[n];\n}',
    options: ['O(2ⁿ)', 'O(n²)', 'O(n)', 'O(n log n)'],
    answer: 2,
    explanation: 'Memoization ensures each sub-problem is solved once. n sub-problems, each O(1) = O(n).',
  },
  {
    type: 'bigO', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'What is the time complexity WITHOUT memoization?',
    code: 'function fib(n) {\n  if (n <= 1) return n;\n  return fib(n - 1) + fib(n - 2);\n}',
    options: ['O(n)', 'O(n²)', 'O(2ⁿ)', 'O(n log n)'],
    answer: 2,
    explanation: 'Without memoization, the recursion tree has ~2ⁿ nodes. Each does O(1) work = O(2ⁿ).',
  },
  {
    type: 'bigO', topic: 'binary-search', difficulty: 'hard',
    prompt: 'What is the time complexity?',
    code: 'function searchMatrix(matrix, target) {\n  let row = 0, col = matrix[0].length - 1;\n  while (row < matrix.length && col >= 0) {\n    if (matrix[row][col] === target) return true;\n    if (matrix[row][col] > target) col--;\n    else row++;\n  }\n  return false;\n}',
    options: ['O(m × n)', 'O(m + n)', 'O(log(m × n))', 'O(m × log n)'],
    answer: 1,
    explanation: 'Starting from top-right, each step eliminates a row or column. At most m + n steps.',
  },

  // ── OUTPUT ─ Easy ─────────────────────────────────────────

  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'let sum = 0;\nfor (let i = 1; i <= 5; i++) {\n  sum += i;\n}\nconsole.log(sum);',
    options: ['10', '15', '5', '6'],
    answer: 1,
    explanation: '1 + 2 + 3 + 4 + 5 = 15.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'const arr = [1, 2, 3, 4, 5];\nconsole.log(arr.slice(1, 3));',
    options: ['[1, 2, 3]', '[2, 3]', '[2, 3, 4]', '[1, 2]'],
    answer: 1,
    explanation: 'slice(1, 3) returns elements from index 1 up to (not including) index 3 = [2, 3].',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'const arr = [3, 1, 4, 1, 5];\nconsole.log(arr.filter(x => x > 2));',
    options: ['[3, 4, 5]', '[1, 1]', '[3, 4, 1, 5]', '[4, 5]'],
    answer: 0,
    explanation: 'filter keeps elements where x > 2: 3, 4, and 5.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'console.log(10 % 3);',
    options: ['3', '1', '3.33', '0'],
    answer: 1,
    explanation: '10 % 3 is the remainder: 10 ÷ 3 = 3 remainder 1.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'const map = new Map();\nmap.set("a", 1);\nmap.set("b", 2);\nmap.set("a", 3);\nconsole.log(map.get("a"));',
    options: ['1', '3', 'undefined', 'Error'],
    answer: 1,
    explanation: 'Setting the same key again overwrites the value. "a" was updated from 1 to 3.',
  },
  {
    type: 'output', topic: 'stacks-queues', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'const queue = [];\nqueue.push("a");\nqueue.push("b");\nqueue.push("c");\nconsole.log(queue.shift());\nconsole.log(queue.shift());',
    options: ['c then b', 'a then b', 'b then c', 'a then c'],
    answer: 1,
    explanation: 'Queue is FIFO. shift() removes from the front: first "a", then "b".',
  },
  {
    type: 'output', topic: 'recursion-backtracking', difficulty: 'easy',
    prompt: 'What does this code output?',
    code: 'function power(base, exp) {\n  if (exp === 0) return 1;\n  return base * power(base, exp - 1);\n}\nconsole.log(power(2, 4));',
    options: ['8', '16', '4', '32'],
    answer: 1,
    explanation: '2⁴ = 2 × 2 × 2 × 2 = 16.',
  },

  // ── OUTPUT ─ Medium ───────────────────────────────────────

  {
    type: 'output', topic: 'recursion-backtracking', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'function countdown(n) {\n  if (n === 0) return;\n  countdown(n - 1);\n  console.log(n);\n}\ncountdown(3);',
    options: ['3 2 1', '1 2 3', '3 2 1 0', '0 1 2 3'],
    answer: 1,
    explanation: 'The recursive call happens before the log, so the deepest call prints first: 1, 2, 3.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'const arr = [1, 2, 3, 4, 5];\nconst result = arr.reduce((acc, val) => {\n  return val % 2 === 0 ? acc + val : acc;\n}, 0);\nconsole.log(result);',
    options: ['15', '6', '9', '2'],
    answer: 1,
    explanation: 'reduce sums only even numbers: 2 + 4 = 6.',
  },
  {
    type: 'output', topic: 'stacks-queues', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'const stack = [];\nstack.push(1);\nstack.push(2);\nstack.push(3);\nstack.pop();\nstack.push(4);\nconsole.log(stack);',
    options: ['[1, 2, 3, 4]', '[1, 2, 4]', '[1, 4]', '[4, 2, 1]'],
    answer: 1,
    explanation: 'Push 1,2,3 → pop removes 3 → push 4 → [1, 2, 4].',
  },
  {
    type: 'output', topic: 'recursion-backtracking', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'function mystery(n) {\n  if (n <= 0) return 0;\n  return n + mystery(n - 2);\n}\nconsole.log(mystery(5));',
    options: ['15', '9', '5', '6'],
    answer: 1,
    explanation: 'mystery(5) = 5 + 3 + 1 + 0 = 9. Steps down by 2 each call.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'const set = new Set([1, 2, 3, 2, 1]);\nset.add(4);\nset.delete(2);\nconsole.log([...set]);',
    options: ['[1, 3, 4]', '[1, 2, 3, 4]', '[1, 3, 2, 4]', '[3, 4]'],
    answer: 0,
    explanation: 'Set removes duplicates: {1,2,3}. Add 4 → {1,2,3,4}. Delete 2 → {1,3,4}.',
  },
  {
    type: 'output', topic: 'arrays-hashing', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'const arr = [10, 9, 2, 1, 100];\narr.sort();\nconsole.log(arr);',
    options: ['[1, 2, 9, 10, 100]', '[100, 10, 9, 2, 1]', '[1, 10, 100, 2, 9]', '[1, 100, 10, 2, 9]'],
    answer: 2,
    explanation: 'JS sort() converts to strings by default. "1" < "10" < "100" < "2" < "9" lexicographically.',
  },
  {
    type: 'output', topic: 'dynamic-programming', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'function maxSubarray(arr) {\n  let max = arr[0], current = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    current = Math.max(arr[i], current + arr[i]);\n    max = Math.max(max, current);\n  }\n  return max;\n}\nconsole.log(maxSubarray([-2,1,-3,4,-1,2,1,-5,4]));',
    options: ['4', '6', '7', '5'],
    answer: 1,
    explanation: 'Kadane\'s algorithm: the max subarray is [4,-1,2,1] = 6.',
  },
  {
    type: 'output', topic: 'two-pointers', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'function compress(s) {\n  let result = "";\n  let i = 0;\n  while (i < s.length) {\n    let j = i;\n    while (j < s.length && s[j] === s[i]) j++;\n    result += s[i] + (j - i);\n    i = j;\n  }\n  return result;\n}\nconsole.log(compress("aaabbc"));',
    options: ['a3b2c1', 'abc', 'a3b2c', '321'],
    answer: 0,
    explanation: 'Groups: "aaa"→a3, "bb"→b2, "c"→c1. Result = "a3b2c1".',
  },
  {
    type: 'output', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'What does this code output?',
    code: 'function inorder(node) {\n  if (!node) return [];\n  return [\n    ...inorder(node.left),\n    node.val,\n    ...inorder(node.right)\n  ];\n}\nconst tree = {\n  val: 4,\n  left: { val: 2, left: { val: 1, left: null, right: null },\n    right: { val: 3, left: null, right: null } },\n  right: { val: 6, left: { val: 5, left: null, right: null },\n    right: null }\n};\nconsole.log(inorder(tree));',
    options: ['[4,2,1,3,6,5]', '[1,2,3,4,5,6]', '[1,3,2,5,6,4]', '[4,2,6,1,3,5]'],
    answer: 1,
    explanation: 'Inorder on a BST gives sorted order: left, root, right → [1,2,3,4,5,6].',
  },

  // ── OUTPUT ─ Hard ─────────────────────────────────────────

  {
    type: 'output', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'What does this code output?',
    code: 'function climb(n, memo = {}) {\n  if (n <= 1) return 1;\n  if (memo[n]) return memo[n];\n  memo[n] = climb(n-1, memo) + climb(n-2, memo);\n  return memo[n];\n}\nconsole.log(climb(5));',
    options: ['5', '8', '13', '3'],
    answer: 1,
    explanation: 'Stair climbing: climb(5) = climb(4)+climb(3) = 5+3 = 8. Sequence: 1,1,2,3,5,8.',
  },
  {
    type: 'output', topic: 'two-pointers', difficulty: 'hard',
    prompt: 'What does this code output?',
    code: 'function reverse(arr) {\n  let l = 0, r = arr.length - 1;\n  while (l < r) {\n    [arr[l], arr[r]] = [arr[r], arr[l]];\n    l++; r--;\n  }\n  return arr;\n}\nconsole.log(reverse([1,2,3,4,5]));',
    options: ['[5,4,3,2,1]', '[1,2,3,4,5]', '[5,4,3,4,5]', '[1,5,3,2,4]'],
    answer: 0,
    explanation: 'Two pointers swap from ends inward: 1↔5, 2↔4, 3 stays → [5,4,3,2,1].',
  },
  {
    type: 'output', topic: 'trees-graphs', difficulty: 'hard',
    prompt: 'What does this code output?',
    code: 'function maxDepth(node) {\n  if (!node) return 0;\n  return 1 + Math.max(\n    maxDepth(node.left), maxDepth(node.right)\n  );\n}\nconst tree = {\n  val: 1,\n  left: { val: 2,\n    left: { val: 4, left: null, right: null },\n    right: null },\n  right: { val: 3, left: null, right: null }\n};\nconsole.log(maxDepth(tree));',
    options: ['2', '3', '4', '1'],
    answer: 1,
    explanation: 'Deepest path is 1→2→4 = depth 3.',
  },
  {
    type: 'output', topic: 'sliding-window', difficulty: 'hard',
    prompt: 'What does this code output?',
    code: 'function maxSum(arr, k) {\n  let sum = 0;\n  for (let i = 0; i < k; i++) sum += arr[i];\n  let max = sum;\n  for (let i = k; i < arr.length; i++) {\n    sum += arr[i] - arr[i - k];\n    max = Math.max(max, sum);\n  }\n  return max;\n}\nconsole.log(maxSum([2,1,5,1,3,2], 3));',
    options: ['8', '9', '10', '7'],
    answer: 1,
    explanation: 'Windows of 3: [2,1,5]=8, [1,5,1]=7, [5,1,3]=9, [1,3,2]=6. Max = 9.',
  },
  {
    type: 'output', topic: 'binary-search', difficulty: 'hard',
    prompt: 'What does this code output?',
    code: 'function lowerBound(arr, target) {\n  let lo = 0, hi = arr.length;\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (arr[mid] < target) lo = mid + 1;\n    else hi = mid;\n  }\n  return lo;\n}\nconsole.log(lowerBound([1,3,3,5,7], 3));',
    options: ['1', '2', '3', '0'],
    answer: 0,
    explanation: 'Lower bound finds first position where value >= target. Index 1 has the first 3.',
  },

  // ── BUG SPOT ─ Easy ───────────────────────────────────────

  {
    type: 'bugspot', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'This should return the sum of an array. What\'s the bug?',
    code: 'function sum(arr) {\n  let total = 0;\n  for (let i = 0; i <= arr.length; i++) {\n    total += arr[i];\n  }\n  return total;\n}',
    options: ['total should start at 1', 'Loop uses <= instead of <', 'arr[i] should be arr[i-1]', 'return should be inside the loop'],
    answer: 1,
    explanation: 'i <= arr.length goes one past the end, adding undefined (NaN). Should be i < arr.length.',
  },
  {
    type: 'bugspot', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'This should find the max value. What\'s the bug?',
    code: 'function findMax(arr) {\n  let max = 0;\n  for (const num of arr) {\n    if (num > max) max = num;\n  }\n  return max;\n}',
    options: ['Should use <= instead of >', 'max should start at -Infinity', 'Should use indexed loop', 'Missing return'],
    answer: 1,
    explanation: 'If all numbers are negative, max stays 0. Initialize with -Infinity or arr[0].',
  },
  {
    type: 'bugspot', topic: 'recursion-backtracking', difficulty: 'easy',
    prompt: 'This should calculate factorial. What\'s the bug?',
    code: 'function factorial(n) {\n  if (n === 0) return 1;\n  return n * factorial(n);\n}',
    options: ['Base case should return 0', 'Should be factorial(n - 1)', 'Should use a loop', 'n === 0 should be n === 1'],
    answer: 1,
    explanation: 'factorial(n) calls factorial(n) — infinite recursion! Should be factorial(n - 1).',
  },
  {
    type: 'bugspot', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'This should check if a value exists. What\'s the bug?',
    code: 'function contains(arr, target) {\n  for (const item of arr) {\n    if (item === target) return true;\n    else return false;\n  }\n}',
    options: ['Should use == not ===', 'Returns false on first non-match', 'Missing default return', 'Should use indexOf'],
    answer: 1,
    explanation: 'The else immediately returns false if the first element doesn\'t match. Move return false after the loop.',
  },
  {
    type: 'bugspot', topic: 'stacks-queues', difficulty: 'easy',
    prompt: 'This should reverse a string using a stack. What\'s the bug?',
    code: 'function reverseStr(s) {\n  const stack = [];\n  for (const ch of s) stack.push(ch);\n  let result = "";\n  while (stack.length > 0) {\n    result += stack.shift();\n  }\n  return result;\n}',
    options: ['push should be unshift', 'shift should be pop', 'result should be an array', 'Loop condition is wrong'],
    answer: 1,
    explanation: 'shift() removes from the front (FIFO). For a stack, use pop() to get LIFO order.',
  },
  {
    type: 'bugspot', topic: 'arrays-hashing', difficulty: 'easy',
    prompt: 'This should count vowels in a string. What\'s the bug?',
    code: 'function countVowels(s) {\n  let count = 0;\n  const vowels = "aeiou";\n  for (const ch of s) {\n    if (vowels.includes(ch)) count++;\n  }\n  return count;\n}',
    options: ['No bug — this is correct', 'Should use indexOf', 'Doesn\'t handle uppercase', 'Count should start at 1'],
    answer: 2,
    explanation: 'The vowels string only has lowercase. "A","E" etc. won\'t match. Convert ch to lowercase first.',
  },

  // ── BUG SPOT ─ Medium ─────────────────────────────────────

  {
    type: 'bugspot', topic: 'binary-search', difficulty: 'medium',
    prompt: 'This binary search has a subtle bug. What is it?',
    code: 'function binarySearch(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) / 2;\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}',
    options: ['lo should start at 1', 'mid isn\'t rounded to an integer', 'while should use <', 'hi should be arr.length'],
    answer: 1,
    explanation: '(lo + hi) / 2 can be non-integer in JS. Use Math.floor() or >> 1.',
  },
  {
    type: 'bugspot', topic: 'two-pointers', difficulty: 'medium',
    prompt: 'This merges two sorted arrays. What\'s the bug?',
    code: 'function merge(a, b) {\n  const result = [];\n  let i = 0, j = 0;\n  while (i < a.length && j < b.length) {\n    if (a[i] <= b[j]) result.push(a[i++]);\n    else result.push(b[j++]);\n  }\n  return result;\n}',
    options: ['Should use < instead of <=', 'Missing remaining elements after loop', 'i and j should start at 1', 'Result should be pre-allocated'],
    answer: 1,
    explanation: 'When one array is exhausted, the remaining elements of the other are lost. Add them after the loop.',
  },
  {
    type: 'bugspot', topic: 'trees-graphs', difficulty: 'medium',
    prompt: 'This BFS should find shortest path but has a bug. What is it?',
    code: 'function bfs(graph, start, end) {\n  const queue = [start];\n  const visited = new Set();\n  let steps = 0;\n  while (queue.length > 0) {\n    const node = queue.shift();\n    if (node === end) return steps;\n    for (const neighbor of graph[node]) {\n      if (!visited.has(neighbor)) {\n        queue.push(neighbor);\n      }\n    }\n    steps++;\n  }\n  return -1;\n}',
    options: ['Should use a stack', 'Nodes never marked as visited', 'steps should start at 1', 'shift should be pop'],
    answer: 1,
    explanation: 'Neighbors are enqueued but never added to visited. This causes infinite revisiting.',
  },
  {
    type: 'bugspot', topic: 'sliding-window', difficulty: 'medium',
    prompt: 'This sliding window finds max sum of k elements. What\'s the bug?',
    code: 'function maxSum(arr, k) {\n  let sum = 0, max = 0;\n  for (let i = 0; i < arr.length; i++) {\n    sum += arr[i];\n    if (i >= k) sum -= arr[i - k];\n    max = Math.max(max, sum);\n  }\n  return max;\n}',
    options: ['max updates before window has k elements', 'sum -= should use i - k + 1', 'Initial max should be -Infinity', 'Loop should start at k'],
    answer: 0,
    explanation: 'max is updated when the window has fewer than k elements. Only compare when i >= k - 1.',
  },
  {
    type: 'bugspot', topic: 'dynamic-programming', difficulty: 'medium',
    prompt: 'This DP coin change has a bug. What is it?',
    code: 'function coinChange(coins, amount) {\n  const dp = new Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (const coin of coins) {\n    for (let i = coin; i <= amount; i++) {\n      dp[i] = Math.min(dp[i], dp[i - coin]);\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}',
    options: ['dp[0] should be 1', 'Missing + 1 in transition', 'Loop should go backwards', 'Should use dp[i-1]'],
    answer: 1,
    explanation: 'dp[i - coin] is the count for that sub-amount. Need dp[i - coin] + 1 to count the current coin.',
  },
  {
    type: 'bugspot', topic: 'recursion-backtracking', difficulty: 'medium',
    prompt: 'This should flatten a nested array. What\'s the bug?',
    code: 'function flatten(arr) {\n  const result = [];\n  for (const item of arr) {\n    if (Array.isArray(item)) {\n      result.push(flatten(item));\n    } else {\n      result.push(item);\n    }\n  }\n  return result;\n}',
    options: ['Should use concat for arrays', 'Base case is missing', 'Should spread: push(...flatten(item))', 'Loop should use index'],
    answer: 2,
    explanation: 'push(flatten(item)) nests the result. Use push(...flatten(item)) to spread elements flat.',
  },

  // ── BUG SPOT ─ Hard ───────────────────────────────────────

  {
    type: 'bugspot', topic: 'recursion-backtracking', difficulty: 'hard',
    prompt: 'This finds all permutations. What\'s the bug?',
    code: 'function permute(nums) {\n  const result = [];\n  function backtrack(path) {\n    if (path.length === nums.length) {\n      result.push(path);\n      return;\n    }\n    for (const num of nums) {\n      if (path.includes(num)) continue;\n      path.push(num);\n      backtrack(path);\n      path.pop();\n    }\n  }\n  backtrack([]);\n  return result;\n}',
    options: ['path.includes is O(n), use Set', 'result.push(path) should be push([...path])', 'path.pop() should be shift()', 'Base case should use >'],
    answer: 1,
    explanation: 'path is mutated after being pushed. Push a copy with [...path] to preserve each permutation.',
  },
  {
    type: 'bugspot', topic: 'trees-graphs', difficulty: 'hard',
    prompt: 'This cycle detection in a directed graph has a bug. What is it?',
    code: 'function hasCycle(graph, n) {\n  const visited = new Set();\n  function dfs(node) {\n    if (visited.has(node)) return true;\n    visited.add(node);\n    for (const nb of graph[node]) {\n      if (dfs(nb)) return true;\n    }\n    return false;\n  }\n  for (let i = 0; i < n; i++) {\n    if (!visited.has(i) && dfs(i)) return true;\n  }\n  return false;\n}',
    options: ['Should use BFS', 'Needs separate "in current path" set', 'visited should be an array', 'Missing leaf node base case'],
    answer: 1,
    explanation: 'A single visited set can\'t distinguish back edges from cross edges. Need a "recursion stack" set.',
  },
  {
    type: 'bugspot', topic: 'dynamic-programming', difficulty: 'hard',
    prompt: 'This 0/1 knapsack has a directional bug. What is it?',
    code: 'function knapsack(weights, values, capacity) {\n  const dp = new Array(capacity + 1).fill(0);\n  for (let i = 0; i < weights.length; i++) {\n    for (let w = weights[i]; w <= capacity; w++) {\n      dp[w] = Math.max(dp[w], dp[w-weights[i]] + values[i]);\n    }\n  }\n  return dp[capacity];\n}',
    options: ['dp should be 2D', 'Inner loop should go right to left', 'Should use values[w]', 'Missing base case'],
    answer: 1,
    explanation: 'For 0/1 knapsack with 1D DP, iterate right-to-left to avoid reusing the same item. Left-to-right = unbounded.',
  },
  {
    type: 'bugspot', topic: 'binary-search', difficulty: 'hard',
    prompt: 'This should find the first bad version. What\'s the bug?',
    code: 'function firstBadVersion(n, isBad) {\n  let lo = 1, hi = n;\n  while (lo < hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (isBad(mid)) hi = mid - 1;\n    else lo = mid + 1;\n  }\n  return lo;\n}',
    options: ['lo should start at 0', 'hi = mid - 1 should be hi = mid', 'while should use <=', 'Should return hi'],
    answer: 1,
    explanation: 'When mid is bad, it might be the first bad version. Keep it in range: hi = mid (not mid - 1).',
  },
  {
    type: 'bugspot', topic: 'arrays-hashing', difficulty: 'hard',
    prompt: 'This LRU Cache has a bug. What is it?',
    code: 'class LRUCache {\n  constructor(cap) {\n    this.cap = cap;\n    this.map = new Map();\n  }\n  get(key) {\n    if (!this.map.has(key)) return -1;\n    return this.map.get(key);\n  }\n  put(key, value) {\n    if (this.map.size >= this.cap) {\n      const first = this.map.keys().next().value;\n      this.map.delete(first);\n    }\n    this.map.set(key, value);\n  }\n}',
    options: ['Should use Object not Map', 'get() doesn\'t refresh the key\'s position', 'put() should check existing key first', 'Capacity check should use >'],
    answer: 1,
    explanation: 'get() should delete and re-insert the key to move it to "most recent". Otherwise eviction order is wrong.',
  },
  {
    type: 'bugspot', topic: 'stacks-queues', difficulty: 'hard',
    prompt: 'This "daily temperatures" solution has a bug. What is it?',
    code: 'function dailyTemps(temps) {\n  const result = new Array(temps.length).fill(0);\n  const stack = [];\n  for (let i = 0; i < temps.length; i++) {\n    while (stack.length && temps[stack[stack.length-1]] < temps[i]) {\n      const idx = stack.pop();\n      result[idx] = idx - i;\n    }\n    stack.push(i);\n  }\n  return result;\n}',
    options: ['Stack should store temps not indices', 'result[idx] should be i - idx', 'while should use <=', 'Should iterate right to left'],
    answer: 1,
    explanation: 'Days to wait = i - idx (future minus past), not idx - i which gives negative.',
  },
];
